### ISSUE TITLE
Generic Palette colors bug on iPad/iPhone

### ISSUE THREAD

**Issue by webcthulhu** [brianpkelley/md-color-picker#84] opened 2016-08-22 10:37 UTC
Hi! 
For some reason only grey spectrum generated in generic palette on iPhone and iPad (not tested this on other devices though). File attached.
I didn't delve deep into the code, so can't tell any assumptions at the moment.

![generic-palette-bug](https://cloud.githubusercontent.com/assets/8151247/17852040/c841e6a6-686d-11e6-91cd-90edc04a7224.png)

**Comment by brianpkelley** [comment] 2016-09-14 20:54
Duplicate of #80

**Comment by brianpkelley** [comment] 2016-09-14 20:57
If the presents it self as a bug after a fix for #80 is added I'll reopen

**Closed as completed** 2016-09-14 20:56 UTC
Labels: duplicate

**Comment by webcthulhu** [comment] 2016-09-19 13:55
Sorry, was inattentive. No, I'm sure it's a same bug.

You need to set height of '.md-color-picker-palette':
.md-color-picker-palette {
  height: 25.5px;
}
or as proposed in #80.
